# Generated by Django 3.2.9 on 2021-12-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwords',
            new_name='Password',
        ),
    ]
