name: deploy
on: 
  push:
    branch:
      - master

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "passme-api"
          heroku_email: ${{ secrets.EMAIL }}
          appdir: "backend"
          usedocker : true
